[toolchain]
#IF option("riscv")
#IF option("stack-protector")
channel = "nightly"
#ELSE
#+channel = "stable"
#ENDIF
components = ["rust-src"]
#REPLACE riscv32imac-unknown-none-elf rust_target
targets = ["riscv32imac-unknown-none-elf"]
#ENDIF
#IF option("xtensa")
#+channel = "esp"
#ENDIF
