[package]
name = "esp-generate"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }

ratatui = { version = "0.28.1", features = ["crossterm"] }
crossterm = { version = "0.28.1" } # Maybe this gives Windows issues like espflash?
rhai = "1.19.0"

[build-dependencies]
walkdir = "2.5.0"
quote = "1.0.37"
