[package]
name    = "esp-generate"
version = "0.1.0"
edition = "2021"

[dependencies]
clap         = { version = "4.5.20", features = ["derive"] }
crossterm    = { version = "0.28.1" }                           # Maybe this gives Windows issues like espflash?
esp-metadata = { version = "0.4.0", features = ["clap"] }
ratatui      = { version = "0.29.0", features = ["crossterm"] }
rhai         = "1.19.0"

[build-dependencies]
quote   = "1.0.37"
walkdir = "2.5.0"
