#REPLACE riscv32imac-unknown-none-elf rust_target
[target.riscv32imac-unknown-none-elf]
#IF !contains_option(probe-rs)
runner = "espflash flash --monitor"
#ENDIF
#IF contains_option(probe-rs)
#REPLACE esp32c6 mcu
#+runner = "probe-rs run --chip=esp32c6"
#ENDIF

[env]
#IF !contains_option(probe-rs)
ESP_LOGLEVEL="INFO"
#ENDIF
#IF contains_option(probe-rs)
DEFMT_LOG="info"
#ENDIF

[build]
rustflags = [
#IF contains_option(xtensa)
  "-C", "link-arg=-nostartfiles",
#ENDIF
#IF contains_option(riscv)
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
#ENDIF
#IF contains_option(stack-protector)
  "-Z", "stack-protector=all",
#ENDIF
]

#REPLACE riscv32imac-unknown-none-elf rust_target
target = "riscv32imac-unknown-none-elf"

[unstable]
#IF contains_option(alloc)
build-std = ["alloc", "core"]
#ENDIF
#IF !contains_option(alloc)
#+build-std = ["core"]
#ENDIF
