#REPLACE riscv32imac-unknown-none-elf rust_target
[target.riscv32imac-unknown-none-elf]
#IF !option("probe-rs")
runner = "espflash flash --monitor"
#ENDIF
#IF option("probe-rs")
#REPLACE esp32c6 mcu
#+runner = "probe-rs run --chip=esp32c6"
#ENDIF

[env]
#IF !option("probe-rs")
ESP_LOGLEVEL="INFO"
#ENDIF
#IF option("probe-rs")
DEFMT_LOG="info"
#ENDIF

[build]
rustflags = [
#IF option("xtensa")
  "-C", "link-arg=-nostartfiles",
#ENDIF
#IF option("riscv")
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
#ENDIF
#IF option("stack-protector")
  "-Z", "stack-protector=all",
#ENDIF
]

#REPLACE riscv32imac-unknown-none-elf rust_target
target = "riscv32imac-unknown-none-elf"

[unstable]
#IF option("alloc")
build-std = ["alloc", "core"]
#ENDIF
#IF !option("alloc")
#+build-std = ["core"]
#ENDIF
